version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: techloom_postgres
    restart: always
    environment:
      POSTGRES_USER: techloom_user
      POSTGRES_PASSWORD: TechloomSecure2026!
      POSTGRES_MULTIPLE_DATABASES: techloom_pos,techloom_ecomm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh:ro

volumes:
  postgres_data:
